"""
pdf_converters.py — Production-grade document conversion routines
Supported Conversions:
- PDF -> Word (.docx) via pdf2docx + PyMuPDF fallback
- PDF -> PowerPoint (.pptx) via PyMuPDF + python-pptx
- PDF -> Excel (.xlsx) via pdfplumber + openpyxl
- Word (.docx) -> PDF via python-docx + reportlab
- PowerPoint (.pptx) -> PDF via python-pptx + reportlab
- Excel (.xlsx) -> PDF via openpyxl + reportlab
"""

import io
import os
import tempfile
import re
from typing import Optional

def _clean_docx_layout(docx_path: str, orig_page_count: int):
    """
    Post-processes a DOCX generated by pdf2docx:
    1. Normalizes section breaks:
       - Preserves legitimate page transitions (new page sections).
       - Ensures intra-page column transitions use continuous breaks so they don't fracture a page.
    2. Clamps excessive paragraph vertical spacing (space_before / space_after) to prevent
       accidental page overflows that push footers or bottom lines onto extra pages.
    """
    try:
        import docx
        from docx.shared import Pt
        from docx.oxml import parse_xml

        doc = docx.Document(docx_path)
        
        # If single-page PDF, all section breaks should be continuous
        if orig_page_count == 1:
            for p in doc.paragraphs:
                for sect in p._p.xpath('.//w:sectPr'):
                    types = sect.xpath('./w:type')
                    if not types:
                        sect.insert(0, parse_xml('<w:type xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:val="continuous"/>'))
                    else:
                        for t in types:
                            t.set('{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val', 'continuous')
        else:
            # Multi-page PDF: fix invalid 'nextColumn' section breaks to continuous
            for p in doc.paragraphs:
                for sect in p._p.xpath('.//w:sectPr'):
                    types = sect.xpath('./w:type')
                    for t in types:
                        val = t.get('{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val')
                        if val == 'nextColumn':
                            t.set('{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val', 'continuous')

        # Paragraph spacing normalization: clamp excessive vertical spacing
        for p in doc.paragraphs:
            fmt = p.paragraph_format
            if fmt.space_before and fmt.space_before.pt > 20:
                fmt.space_before = Pt(10)
            if fmt.space_after and fmt.space_after.pt > 20:
                fmt.space_after = Pt(10)
            
            # Trim spacing on empty spacer paragraphs
            if not p.text.strip() and not p._p.xpath('.//w:drawing'):
                if fmt.space_before and fmt.space_before.pt > 10:
                    fmt.space_before = Pt(4)
                if fmt.space_after and fmt.space_after.pt > 10:
                    fmt.space_after = Pt(4)
                    
        doc.save(docx_path)
    except Exception as e:
        print(f"[Warning] Post-processing DOCX layout: {e}")

def _structured_fallback_pdf_to_docx(pdf_bytes: bytes) -> bytes:
    """
    High-fidelity fallback converter using PyMuPDF and python-docx:
    - Extracts structured text blocks preserving font size, weight, italic, and color
    - Extracts and embeds native images
    - Handles scanned / image-only pages via full-page high-resolution embedding
    - Preserves multi-page flow and page breaks
    """
    import fitz
    import docx
    from docx.shared import Pt, Inches, RGBColor

    doc = docx.Document()
    pdf_doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    
    for page_idx, page in enumerate(pdf_doc):
        if page_idx > 0:
            doc.add_page_break()
            
        rect = page.rect
        text_content = page.get_text("text").strip()
        img_list = page.get_images()
        
        # Scanned page check (< 30 characters and has images)
        if len(text_content) < 30 and len(img_list) > 0:
            pix = page.get_pixmap(dpi=200)
            doc.add_picture(io.BytesIO(pix.tobytes("png")), width=Inches(min(rect.width / 72.0, 6.5)))
            continue
            
        text_dict = page.get_text("dict")
        blocks = text_dict.get("blocks", [])
        
        for b in blocks:
            b_type = b.get("type", 0)
            if b_type == 0:  # Text block
                for line in b.get("lines", []):
                    spans = line.get("spans", [])
                    if not spans:
                        continue
                    p = doc.add_paragraph()
                    p.paragraph_format.space_before = Pt(1)
                    p.paragraph_format.space_after = Pt(2)
                    p.paragraph_format.line_spacing = 1.05
                    
                    for s in spans:
                        raw_text = s.get("text", "")
                        if not raw_text:
                            continue
                        r = p.add_run(raw_text)
                        size = s.get("size", 10.5)
                        r.font.size = Pt(min(max(size, 7), 36))
                        flags = s.get("flags", 0)
                        font_name = s.get("font", "").lower()
                        r.font.bold = bool(flags & 2) or ("bold" in font_name)
                        r.font.italic = bool(flags & 1) or ("italic" in font_name or "oblique" in font_name)
                        
                        col = s.get("color", 0)
                        if col > 0:
                            cr = (col >> 16) & 0xFF
                            cg = (col >> 8) & 0xFF
                            cb = col & 0xFF
                            r.font.color.rgb = RGBColor(cr, cg, cb)
                            
            elif b_type == 1:  # Image block
                img_bytes = b.get("image")
                if img_bytes:
                    try:
                        bbox = b.get("bbox", [0, 0, 100, 100])
                        w_in = max((bbox[2] - bbox[0]) / 72.0, 0.5)
                        doc.add_picture(io.BytesIO(img_bytes), width=Inches(min(w_in, 6.0)))
                    except Exception:
                        pass

    out_stream = io.BytesIO()
    doc.save(out_stream)
    return out_stream.getvalue()

def pdf_to_docx(pdf_bytes: bytes) -> bytes:
    """
    Converts PDF document bytes into an editable Microsoft Word (.docx) document.
    Architecture:
      1. Primary engine: pdf2docx with tuned parameters:
         - parse_stream_table=False (prevents fake borderless tables from mangling resumes/columns)
         - parse_lattice_table=True (preserves genuine bordered tables)
         - multi_processing=False (container-safe execution)
      2. Post-processing layout pass:
         - Normalizes section breaks (continuous intra-page transitions)
         - Clamps excessive paragraph spacing to prevent footer/page overflow
      3. Fallback engine: Structured PyMuPDF + python-docx extractor preserving
         typography, colors, images, and page structure.
    """
    temp_pdf = None
    temp_docx = None
    try:
        from pdf2docx import Converter
        import fitz
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f_pdf:
            f_pdf.write(pdf_bytes)
            temp_pdf = f_pdf.name
        temp_docx = temp_pdf.replace(".pdf", ".docx")
        
        orig_page_count = 1
        try:
            with fitz.open(stream=pdf_bytes, filetype="pdf") as pdoc:
                orig_page_count = len(pdoc)
        except Exception:
            pass
            
        cv = Converter(temp_pdf)
        cv.convert(
            temp_docx,
            start=0,
            end=None,
            parse_stream_table=False,
            parse_lattice_table=True,
            multi_processing=False
        )
        cv.close()
        
        _clean_docx_layout(temp_docx, orig_page_count=orig_page_count)
        
        with open(temp_docx, "rb") as f_out:
            return f_out.read()
    except Exception as e:
        print(f"[pdf_to_docx primary engine warning: {e}, using structured fallback]")
        return _structured_fallback_pdf_to_docx(pdf_bytes)
    finally:
        if temp_pdf and os.path.exists(temp_pdf):
            try: os.remove(temp_pdf)
            except Exception: pass
        if temp_docx and os.path.exists(temp_docx):
            try: os.remove(temp_docx)
            except Exception: pass


def pdf_to_pptx(pdf_bytes: bytes) -> bytes:
    """
    Converts PDF document pages into editable hybrid PowerPoint slides (.pptx).
    Architecture:
      - Inspects each page for extractable text, images, and vector shapes.
      - Scanned / image-only pages (<30 chars, no drawings) fall back to high-res full-page rendering.
      - Hybrid pages construct:
          1. Solid background color (detected from full-page vector canvas).
          2. Native editable vector shapes (rectangles, rounded rectangles, divider lines).
          3. Extracted native image objects (preserves position, size, and original resolution).
          4. Native editable text boxes with matched font family, size, weight, italic, and RGB color.
      - Slide dimensions match each PDF page's native aspect ratio (A4, Letter, Custom).
    """
    import fitz
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_SHAPE

    def _color_to_rgb(col):
        if not col:
            return None
        if len(col) == 1:
            val = max(0, min(255, int(col[0] * 255)))
            return RGBColor(val, val, val)
        if len(col) >= 3:
            r = max(0, min(255, int(col[0] * 255)))
            g = max(0, min(255, int(col[1] * 255)))
            b = max(0, min(255, int(col[2] * 255)))
            return RGBColor(r, g, b)
        return None

    def _int_color_to_rgb(val):
        if val is None or val < 0:
            return RGBColor(0, 0, 0)
        return RGBColor((val >> 16) & 0xFF, (val >> 8) & 0xFF, val & 0xFF)

    def _map_font_family(pdf_font):
        if not pdf_font:
            return "Calibri"
        f_lower = pdf_font.lower()
        if any(k in f_lower for k in ["times", "serif", "georgia", "garamond", "minion", "cambria"]):
            return "Georgia"
        if any(k in f_lower for k in ["courier", "mono", "consolas", "menlo"]):
            return "Courier New"
        return "Calibri"

    pdf_doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    prs = Presentation()
    blank_layout = prs.slide_layouts[6]

    for page in pdf_doc:
        rect = page.rect
        width_in = max(rect.width / 72.0, 4.0)
        height_in = max(rect.height / 72.0, 3.0)
        prs.slide_width = Inches(width_in)
        prs.slide_height = Inches(height_in)

        slide = prs.slides.add_slide(blank_layout)

        try:
            text_content = page.get_text("text").strip()
            drawings = page.get_drawings()
            img_list = page.get_images()

            # Detection for scanned / image-only page (no text, no drawings)
            is_scanned = (len(text_content) < 30 and len(img_list) > 0 and len(drawings) == 0)

            if is_scanned:
                pix = page.get_pixmap(dpi=200)
                slide.shapes.add_picture(
                    io.BytesIO(pix.tobytes("png")),
                    Inches(0),
                    Inches(0),
                    width=Inches(width_in),
                    height=Inches(height_in)
                )
                continue

            # Layer 1: Background detection (full-page rectangle fill)
            bg_color = None
            for d in drawings:
                dr = d["rect"]
                if dr.width >= rect.width - 2 and dr.height >= rect.height - 2 and d.get("fill"):
                    bg_color = _color_to_rgb(d.get("fill"))
                    break
            if bg_color:
                slide.background.fill.solid()
                slide.background.fill.fore_color.rgb = bg_color

            # Layer 2: Vector Shapes & Lines
            for d in drawings:
                dr = d["rect"]
                # Skip full-page background canvas already applied
                if dr.width >= rect.width - 2 and dr.height >= rect.height - 2:
                    continue
                fill_c = _color_to_rgb(d.get("fill"))
                stroke_c = _color_to_rgb(d.get("color"))
                items = d.get("items", [])

                # Horizontal divider line
                if dr.height <= 2.5 and (stroke_c or fill_c):
                    c = stroke_c or fill_c
                    line_w = Pt(max(d.get("width", 1), 0.75))
                    shp = slide.shapes.add_shape(
                        MSO_SHAPE.RECTANGLE,
                        Inches(dr.x0 / 72.0),
                        Inches(dr.y0 / 72.0),
                        Inches(dr.width / 72.0),
                        line_w
                    )
                    shp.fill.solid()
                    shp.fill.fore_color.rgb = c
                    shp.line.fill.background()
                # Vertical divider line
                elif dr.width <= 2.5 and (stroke_c or fill_c):
                    c = stroke_c or fill_c
                    line_w = Pt(max(d.get("width", 1), 0.75))
                    shp = slide.shapes.add_shape(
                        MSO_SHAPE.RECTANGLE,
                        Inches(dr.x0 / 72.0),
                        Inches(dr.y0 / 72.0),
                        line_w,
                        Inches(dr.height / 72.0)
                    )
                    shp.fill.solid()
                    shp.fill.fore_color.rgb = c
                    shp.line.fill.background()
                # Filled shapes (rectangles, rounded rectangles, cards)
                elif fill_c:
                    is_rounded = any(it[0] == "c" for it in items)
                    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if is_rounded else MSO_SHAPE.RECTANGLE
                    shp = slide.shapes.add_shape(
                        shape_type,
                        Inches(dr.x0 / 72.0),
                        Inches(dr.y0 / 72.0),
                        Inches(dr.width / 72.0),
                        Inches(dr.height / 72.0)
                    )
                    shp.fill.solid()
                    shp.fill.fore_color.rgb = fill_c
                    if stroke_c:
                        shp.line.color.rgb = stroke_c
                        shp.line.width = Pt(d.get("width", 1))
                    else:
                        shp.line.fill.background()
                    if is_rounded:
                        try:
                            shp.adjustments[0] = 0.05
                        except Exception:
                            pass

            # Layer 3: Extracted native images
            for img_info in img_list:
                xref = img_info[0]
                try:
                    base_img = pdf_doc.extract_image(xref)
                    img_bytes = base_img["image"]
                    for img_rect in page.get_image_rects(xref):
                        slide.shapes.add_picture(
                            io.BytesIO(img_bytes),
                            Inches(img_rect.x0 / 72.0),
                            Inches(img_rect.y0 / 72.0),
                            width=Inches(img_rect.width / 72.0),
                            height=Inches(img_rect.height / 72.0)
                        )
                except Exception:
                    pass

            # Layer 4: Native Editable Text Boxes
            text_dict = page.get_text("dict")
            for b in text_dict.get("blocks", []):
                if "lines" not in b:
                    continue
                for l in b["lines"]:
                    spans = l["spans"]
                    if not spans:
                        continue
                    lx0, ly0 = l["bbox"][0], l["bbox"][1]
                    lw = max(l["bbox"][2] - lx0, 10)
                    lh = max(l["bbox"][3] - ly0, 10)

                    tb = slide.shapes.add_textbox(
                        Inches(lx0 / 72.0),
                        Inches(ly0 / 72.0),
                        Inches(lw / 72.0 + 0.15),
                        Inches(lh / 72.0)
                    )
                    tf = tb.text_frame
                    tf.word_wrap = False
                    tf.margin_left = tf.margin_top = tf.margin_right = tf.margin_bottom = 0
                    p = tf.paragraphs[0]

                    for s in spans:
                        raw_text = s.get("text", "")
                        if not raw_text:
                            continue
                        r = p.add_run()
                        r.text = raw_text
                        r.font.size = Pt(s.get("size", 11))
                        r.font.color.rgb = _int_color_to_rgb(s.get("color"))
                        flags = s.get("flags", 0)
                        font_name = s.get("font", "")
                        r.font.bold = bool(flags & 2) or ("bold" in font_name.lower())
                        r.font.italic = bool(flags & 1) or ("italic" in font_name.lower() or "oblique" in font_name.lower())
                        r.font.name = _map_font_family(font_name)

        except Exception as page_err:
            # Fallback to full-page raster if structured reconstruction encounters an anomaly
            pix = page.get_pixmap(dpi=200)
            slide.shapes.add_picture(
                io.BytesIO(pix.tobytes("png")),
                Inches(0),
                Inches(0),
                width=Inches(width_in),
                height=Inches(height_in)
            )

    out_stream = io.BytesIO()
    prs.save(out_stream)
    return out_stream.getvalue()

def pdf_to_xlsx(pdf_bytes: bytes) -> bytes:
    """Extracts tables and tabular rows from PDF pages into formatted Excel (.xlsx) workbook."""
    import pdfplumber
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    header_font = Font(name="Arial", size=10, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1E40AF", end_color="1E40AF", fill_type="solid")
    regular_font = Font(name="Arial", size=10)
    border_side = Side(border_style="thin", color="E2E8F0")
    thin_border = Border(left=border_side, right=border_side, top=border_side, bottom=border_side)
    center_align = Alignment(vertical="center")

    has_data = False
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for idx, page in enumerate(pdf.pages):
            sheet_title = f"Page {idx + 1}"
            ws = wb.create_sheet(title=sheet_title)
            
            tables = page.extract_tables()
            current_row = 1

            if tables:
                for table in tables:
                    if not table:
                        continue
                    has_data = True
                    for r_idx, row in enumerate(table):
                        if not any(row):
                            continue
                        for c_idx, val in enumerate(row):
                            cell = ws.cell(row=current_row, column=c_idx + 1, value=str(val or "").strip())
                            cell.border = thin_border
                            cell.alignment = center_align
                            if r_idx == 0:
                                cell.font = header_font
                                cell.fill = header_fill
                            else:
                                cell.font = regular_font
                        current_row += 1
                    current_row += 2
            else:
                text = page.extract_text()
                if text:
                    has_data = True
                    for line in text.split("\n"):
                        clean = line.strip()
                        if not clean:
                            continue
                        parts = re.split(r"\s{2,}|\t+", clean)
                        for c_idx, part in enumerate(parts):
                            cell = ws.cell(row=current_row, column=c_idx + 1, value=part.strip())
                            cell.font = regular_font
                            cell.alignment = center_align
                        current_row += 1

            for col in ws.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if cell.value:
                        max_len = max(max_len, len(str(cell.value)))
                ws.column_dimensions[col_letter].width = max(max_len + 3, 10)

    if not has_data or len(wb.sheetnames) == 0:
        ws = wb.create_sheet(title="Data")
        ws.cell(row=1, column=1, value="No tabular data extracted from PDF.")

    out_stream = io.BytesIO()
    wb.save(out_stream)
    return out_stream.getvalue()

def docx_to_pdf(docx_bytes: bytes) -> bytes:
    """Converts Word document (.docx) bytes into a formatted PDF document."""
    from docx import Document
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    doc = Document(io.BytesIO(docx_bytes))
    out_stream = io.BytesIO()
    pdf_doc = SimpleDocTemplate(
        out_stream,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]
    normal_style.fontSize = 10
    normal_style.leading = 14
    
    h1_style = styles["Heading1"]
    h1_style.fontSize = 18
    h1_style.leading = 22
    h1_style.textColor = colors.HexColor("#0F172A")

    h2_style = styles["Heading2"]
    h2_style.fontSize = 14
    h2_style.leading = 18
    h2_style.textColor = colors.HexColor("#1E293B")

    flowables = []

    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            flowables.append(Spacer(1, 8))
            continue
        
        style_name = para.style.name.lower() if para.style else ""
        if "heading 1" in style_name or "title" in style_name:
            flowables.append(Paragraph(text, h1_style))
            flowables.append(Spacer(1, 10))
        elif "heading 2" in style_name:
            flowables.append(Paragraph(text, h2_style))
            flowables.append(Spacer(1, 8))
        else:
            flowables.append(Paragraph(text, normal_style))
            flowables.append(Spacer(1, 6))

    for table in doc.tables:
        table_data = []
        for row in table.rows:
            row_data = [Paragraph(cell.text.strip(), normal_style) for cell in row.cells]
            table_data.append(row_data)
        if table_data:
            t = Table(table_data, colWidths=None)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ]))
            flowables.append(t)
            flowables.append(Spacer(1, 12))

    if not flowables:
        flowables.append(Paragraph("Empty Document", normal_style))

    pdf_doc.build(flowables)
    return out_stream.getvalue()

def pptx_to_pdf(pptx_bytes: bytes) -> bytes:
    """Converts PowerPoint presentation (.pptx) bytes into a multi-page PDF document."""
    from pptx import Presentation
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors

    prs = Presentation(io.BytesIO(pptx_bytes))
    width_pt = prs.slide_width.pt if prs.slide_width else 720
    height_pt = prs.slide_height.pt if prs.slide_height else 540

    out_stream = io.BytesIO()
    c = canvas.Canvas(out_stream, pagesize=(width_pt, height_pt))

    for slide in prs.slides:
        c.setFillColor(colors.white)
        c.rect(0, 0, width_pt, height_pt, fill=1, stroke=0)

        for shape in slide.shapes:
            if shape.has_text_frame:
                tf = shape.text_frame
                left = shape.left.pt
                top = shape.top.pt
                pdf_y = height_pt - top
                
                c.setFillColor(colors.HexColor("#0F172A"))
                y_offset = pdf_y - 14
                for p in tf.paragraphs:
                    line_text = p.text.strip()
                    if line_text:
                        font_size = p.font.size.pt if p.font and p.font.size else 12
                        c.setFont("Helvetica", font_size)
                        c.drawString(left, max(y_offset, 10), line_text)
                        y_offset -= (font_size + 4)
            
            if shape.shape_type == 13:
                try:
                    img_bytes = shape.image.blob
                    img_io = io.BytesIO(img_bytes)
                    img_left = shape.left.pt
                    img_top = shape.top.pt
                    img_w = shape.width.pt
                    img_h = shape.height.pt
                    pdf_y = height_pt - img_top - img_h
                    from reportlab.lib.utils import ImageReader
                    c.drawImage(ImageReader(img_io), img_left, pdf_y, width=img_w, height=img_h)
                except Exception:
                    pass

        c.showPage()

    c.save()
    return out_stream.getvalue()

def xlsx_to_pdf(xlsx_bytes: bytes) -> bytes:
    """Converts Excel spreadsheet (.xlsx) bytes into formatted paginated PDF tables."""
    import openpyxl
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes), data_only=True)
    out_stream = io.BytesIO()
    pdf_doc = SimpleDocTemplate(
        out_stream,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = styles["Heading2"]
    title_style.textColor = colors.HexColor("#0F172A")
    cell_style = styles["Normal"]
    cell_style.fontSize = 8
    cell_style.leading = 10

    flowables = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        flowables.append(Paragraph(f"<b>Sheet: {sheet_name}</b>", title_style))
        flowables.append(Spacer(1, 10))

        rows_data = []
        max_cols = 0
        for row in ws.iter_rows(values_only=True):
            if any(row):
                str_row = [Paragraph(str(val) if val is not None else "", cell_style) for val in row]
                rows_data.append(str_row)
                max_cols = max(max_cols, len(str_row))

        if rows_data:
            for r in rows_data:
                while len(r) < max_cols:
                    r.append(Paragraph("", cell_style))
            
            avail_w = 720
            col_w = max(avail_w / max_cols, 35) if max_cols > 0 else 50
            col_widths = [col_w] * max_cols

            t = Table(rows_data, colWidths=col_widths)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ]))
            flowables.append(t)
        else:
            flowables.append(Paragraph("Empty Worksheet", cell_style))

        flowables.append(Spacer(1, 20))

    if not flowables:
        flowables.append(Paragraph("Empty Workbook", cell_style))

    pdf_doc.build(flowables)
    return out_stream.getvalue()
