export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'pt', name: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'zh', name: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
];

export const TRANSLATIONS = {
  en: {
    browseTools: 'Browse Tools',
    categories: 'Categories',
    blogs: 'Blogs',
    myDashboard: 'My Dashboard',
    admin: 'Admin',
    submitTool: 'Submit Tool',
    signIn: 'Sign In',
    searchPlaceholder: 'Search 700+ AI tools...',
    allCategories: 'All Categories',
    trending: 'Trending',
    newest: 'Newest',
    topRated: 'Top Rated',
    popular: 'Popular',
    footerDescription: 'The world\'s largest directory of free AI tools. Discover, compare, and master the best artificial intelligence solutions.',
    topCategories: 'Top Categories',
    quickLinks: 'Quick Links',
    legalInfo: 'Legal & Info',
    allRightsReserved: 'All rights reserved.',
  },
  es: {
    browseTools: 'Explorar Herramientas',
    categories: 'Categorías',
    blogs: 'Blogs',
    myDashboard: 'Mi Panel',
    admin: 'Admin',
    submitTool: 'Enviar Herramienta',
    signIn: 'Iniciar Sesión',
    searchPlaceholder: 'Buscar +700 herramientas de IA...',
    allCategories: 'Todas las Categorías',
    trending: 'Tendencias',
    newest: 'Más Nuevas',
    topRated: 'Mejor Valoradas',
    popular: 'Populares',
    footerDescription: 'El directorio de herramientas gratuitas de IA más grande del mundo. Descubre y compara las mejores soluciones.',
    topCategories: 'Principales Categorías',
    quickLinks: 'Enlaces Rápidos',
    legalInfo: 'Información Legal',
    allRightsReserved: 'Todos los derechos reservados.',
  },
  fr: {
    browseTools: 'Parcourir les Outils',
    categories: 'Catégories',
    blogs: 'Blogs',
    myDashboard: 'Mon Tableau de Bord',
    admin: 'Admin',
    submitTool: 'Soumettre un Outil',
    signIn: 'Se Connecter',
    searchPlaceholder: 'Rechercher parmi 700+ outils IA...',
    allCategories: 'Toutes les Catégories',
    trending: 'Tendances',
    newest: 'Plus Récents',
    topRated: 'Mieux Notés',
    popular: 'Populaires',
    footerDescription: 'Le plus grand répertoire d\'outils IA gratuits au monde. Découvrez et comparez les meilleures solutions IA.',
    topCategories: 'Meilleures Catégories',
    quickLinks: 'Liens Rapides',
    legalInfo: 'Informations Légales',
    allRightsReserved: 'Tous droits réservés.',
  },
  de: {
    browseTools: 'Tools Durchsuchen',
    categories: 'Kategorien',
    blogs: 'Blogs',
    myDashboard: 'Mein Dashboard',
    admin: 'Admin',
    submitTool: 'Tool Einreichen',
    signIn: 'Anmelden',
    searchPlaceholder: 'Über 700+ KI-Tools suchen...',
    allCategories: 'Alle Kategorien',
    trending: 'Trends',
    newest: 'Neueste',
    topRated: 'Am Besten Bewertet',
    popular: 'Beliebt',
    footerDescription: 'Das weltweit größte Verzeichnis für kostenlose KI-Tools. Entdecken und vergleichen Sie die besten KI-Lösungen.',
    topCategories: 'Top-Kategorien',
    quickLinks: 'Schnelllinks',
    legalInfo: 'Rechtliches & Info',
    allRightsReserved: 'Alle Rechte vorbehalten.',
  },
  pt: {
    browseTools: 'Navegar por Ferramentas',
    categories: 'Categorias',
    blogs: 'Blogs',
    myDashboard: 'Meu Painel',
    admin: 'Admin',
    submitTool: 'Enviar Ferramenta',
    signIn: 'Entrar',
    searchPlaceholder: 'Pesquisar +700 ferramentas de IA...',
    allCategories: 'Todas as Categorias',
    trending: 'Em Alta',
    newest: 'Mais Recentes',
    topRated: 'Mais Avaliadas',
    popular: 'Populares',
    footerDescription: 'O maior diretório do mundo de ferramentas gratuitas de IA. Descubra e compare as melhores soluções de inteligência artificial.',
    topCategories: 'Principais Categorias',
    quickLinks: 'Links Rápidos',
    legalInfo: 'Informações Legais',
    allRightsReserved: 'Todos os direitos reservados.',
  },
  ar: {
    browseTools: 'تصفح الأدوات',
    categories: 'الفئات',
    blogs: 'المدونات',
    myDashboard: 'لوحة التحكم',
    admin: 'الإدارة',
    submitTool: 'إضافة أداة',
    signIn: 'تسجيل الدخول',
    searchPlaceholder: 'ابحث في أكثر من 700 أداة ذكاء اصطناعي...',
    allCategories: 'جميع الفئات',
    trending: 'الأكثر رواجاً',
    newest: 'الأحدث',
    topRated: 'الأعلى تقييماً',
    popular: 'الأكثر شعبية',
    footerDescription: 'أكبر دليل مجاني لأدوات الذكاء الاصطناعي في العالم. اكتشف وقارن أفضل حلول الذكاء الاصطناعي.',
    topCategories: 'أهم الفئات',
    quickLinks: 'روابط سريعة',
    legalInfo: 'معلومات قانونية',
    allRightsReserved: 'جميع الحقوق محفوظة.',
  },
  ru: {
    browseTools: 'Каталог Инструментов',
    categories: 'Категории',
    blogs: 'Блоги',
    myDashboard: 'Панель Управления',
    admin: 'Админ',
    submitTool: 'Добавить Инструмент',
    signIn: 'Войти',
    searchPlaceholder: 'Поиск по 700+ ИИ-инструментам...',
    allCategories: 'Все Категории',
    trending: 'В Тренде',
    newest: 'Новые',
    topRated: 'Лучшие',
    popular: 'Популярные',
    footerDescription: 'Крупнейший в мире каталог бесплатных инструментов ИИ. Находите и сравнивайте лучшие решения искусственного интеллекта.',
    topCategories: 'Популярные Категории',
    quickLinks: 'Быстрые Ссылки',
    legalInfo: 'Правовая Информация',
    allRightsReserved: 'Все права защищены.',
  },
  ja: {
    browseTools: 'ツールを探す',
    categories: 'カテゴリ',
    blogs: 'ブログ',
    myDashboard: 'ダッシュボード',
    admin: '管理者',
    submitTool: 'ツールを投稿',
    signIn: 'ログイン',
    searchPlaceholder: '700以上のAIツールを検索...',
    allCategories: 'すべてのカテゴリ',
    trending: 'トレンド',
    newest: '新着',
    topRated: '高評価',
    popular: '人気',
    footerDescription: '世界最大の無料AIツールディレクトリ。最高の人工知能ソリューションを発見・比較できます。',
    topCategories: '人気カテゴリ',
    quickLinks: 'クイックリンク',
    legalInfo: '法的情報',
    allRightsReserved: 'All rights reserved.',
  },
  zh: {
    browseTools: '浏览 AI 工具',
    categories: '工具分类',
    blogs: '博客文章',
    myDashboard: '个人中心',
    admin: '管理后台',
    submitTool: '提交 AI 工具',
    signIn: '登录',
    searchPlaceholder: '搜索 700+ 款 AI 工具...',
    allCategories: '全部分类',
    trending: '热门趋势',
    newest: '最新发布',
    topRated: '最高好评',
    popular: '最受欢迎',
    footerDescription: '全球最大的免费 AI 工具目录。探索并比较最顶尖的人工智能解决方案。',
    topCategories: '热门分类',
    quickLinks: '快速链接',
    legalInfo: '法律条款',
    allRightsReserved: '保留所有权利。',
  },
  it: {
    browseTools: 'Esplora Strumenti',
    categories: 'Categorie',
    blogs: 'Blog',
    myDashboard: 'La Mia Dashboard',
    admin: 'Admin',
    submitTool: 'Invia Strumento',
    signIn: 'Accedi',
    searchPlaceholder: 'Cerca tra oltre 700 strumenti IA...',
    allCategories: 'Tutte le Categorie',
    trending: 'In Tendenza',
    newest: 'Più Recenti',
    topRated: 'I Più Votati',
    popular: 'Popolari',
    footerDescription: 'La più grande directory al mondo di strumenti IA gratuiti. Scopri e confronta le migliori soluzioni di intelligenza artificiale.',
    topCategories: 'Categorie Principali',
    quickLinks: 'Link Rapidi',
    legalInfo: 'Info Legali',
    allRightsReserved: 'Tutti i diritti riservati.',
  },
  nl: {
    browseTools: 'Tools Bladeren',
    categories: 'Categorieën',
    blogs: 'Blogs',
    myDashboard: 'Mijn Dashboard',
    admin: 'Admin',
    submitTool: 'Tool Inzenden',
    signIn: 'Inloggen',
    searchPlaceholder: 'Zoek in 700+ AI-tools...',
    allCategories: 'Alle Categorieën',
    trending: 'Populair',
    newest: 'Nieuwste',
    topRated: 'Best Beoordeeld',
    popular: 'Favoriet',
    footerDescription: 'Word\'s grootste gids voor gratis AI-tools. Ontdek en vergelijk de beste kunstmatige intelligentie oplossingen.',
    topCategories: 'Top Categorieën',
    quickLinks: 'Snelle Links',
    legalInfo: 'Juridische Info',
    allRightsReserved: 'Alle rechten voorbehouden.',
  },
};
