export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'pt', name: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'zh', name: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
];

export const TRANSLATIONS = {
  en: {
    browseTools: 'Browse Tools',
    categories: 'Categories',
    blogs: 'Blogs',
    myDashboard: 'My Dashboard',
    admin: 'Admin',
    submitTool: 'Submit Tool',
    signIn: 'Sign In',
    searchPlaceholder: 'Search 700+ AI tools...',
    searchBtn: 'Search',
    allCategories: 'All Categories',
    trending: 'Trending',
    newest: 'Newest',
    topRated: 'Top Rated',
    popular: 'Popular',
    heroBadge: 'Join 50,000+ users discovering AI Tools',
    heroTitlePrefix: 'The Ultimate',
    heroTitleSuffix: 'AI Tools Directory',
    heroSubtitle: 'Search 700+ verified AI tools by category. Find the perfect artificial intelligence software for your specific business needs.',
    exploreAllTools: 'Explore All Tools',
    submitYourProject: 'Submit Your Project',
    featuredInnovation: 'Featured Innovation',
    featuredSubtitle: 'Handpicked AI excellence recommended by our experts',
    viewAllExcellence: 'View All Excellence',
    hyperGrowthTools: 'Hyper Growth Tools',
    trendingSubtitle: 'The most searched AI solutions this week',
    seeTrends: 'See Trends',
    discoverByIntent: 'Discover by Intent',
    intentSubtitle: 'Every tool you need, professionally organized for your workflow',
    exploreAllCategories: 'Explore All Categories',
    freshArrivals: 'Fresh Off The Press',
    arrivalsSubtitle: 'Newest AI arrivals in our community',
    recentArrivals: 'Recent Arrivals',
    featureYourProduct: 'Feature Your AI Product',
    ctaSubtitle: 'Join thousands of founders who trust us to grow their AI business.',
    aiApps: 'AI Apps',
    monthlyVisits: 'Monthly Visits',
    freeDirectory: '#1 Free Directory',
    footerDescription: 'The world\'s largest directory of free AI tools. Discover, compare, and master the best artificial intelligence solutions.',
    topCategories: 'Top Categories',
    quickLinks: 'Quick Links',
    legalInfo: 'Legal & Info',
    allRightsReserved: 'All rights reserved.',
    
    // Tool Detail Page Translations
    overviewOf: 'Overview of',
    prosAndConsOf: 'Pros & Cons of',
    pros: 'Pros',
    cons: 'Cons',
    readyToTry: 'Ready to try',
    getStartedFree: 'Get Started Free',
    pricingModel: 'Pricing Model',
    globalRating: 'Global Rating',
    lastUpdated: 'Last Updated',
    similarAiTools: 'Similar AI Tools',
    classification: 'Classification',
    mainCategories: 'Main Categories',
    relatedTopics: 'Related Topics',
    userReviews: 'User Reviews',
    faqTitle: 'Frequently Asked Questions',
    reviews: 'reviews',
    keyBenefits: 'Key Benefits & Features',
    backToTools: 'Back to Tools',
    home: 'Home',
    tools: 'Tools',
  },
  es: {
    browseTools: 'Explorar Herramientas',
    categories: 'Categorías',
    blogs: 'Blogs',
    myDashboard: 'Mi Panel',
    admin: 'Admin',
    submitTool: 'Enviar Herramienta',
    signIn: 'Iniciar Sesión',
    searchPlaceholder: 'Buscar +700 herramientas de IA...',
    searchBtn: 'Buscar',
    allCategories: 'Todas las Categorías',
    trending: 'Tendencias',
    newest: 'Más Nuevas',
    topRated: 'Mejor Valoradas',
    popular: 'Populares',
    heroBadge: 'Únete a más de 50,000 usuarios que descubren herramientas de IA',
    heroTitlePrefix: 'El Directorio Definitivo de',
    heroTitleSuffix: 'Herramientas de IA',
    heroSubtitle: 'Busca en más de 700 herramientas de IA verificadas por categoría. Encuentra el software perfecto para tus necesidades.',
    exploreAllTools: 'Explorar Todas las Herramientas',
    submitYourProject: 'Enviar tu Proyecto',
    featuredInnovation: 'Innovación Destacada',
    featuredSubtitle: 'Excelencia en IA seleccionada por nuestros expertos',
    viewAllExcellence: 'Ver Todas',
    hyperGrowthTools: 'Herramientas de Alto Crecimiento',
    trendingSubtitle: 'Las soluciones de IA más buscadas de la semana',
    seeTrends: 'Ver Tendencias',
    discoverByIntent: 'Descubrir por Categoría',
    intentSubtitle: 'Todas las herramientas organizadas profesionalmente para tu flujo de trabajo',
    exploreAllCategories: 'Explorar Todas las Categorías',
    freshArrivals: 'Novedades Recientes',
    arrivalsSubtitle: 'Las últimas incorporaciones de IA en nuestra comunidad',
    recentArrivals: 'Llegadas Recientes',
    featureYourProduct: 'Destaca tu Producto de IA',
    ctaSubtitle: 'Únete a miles de creadores que confían en nosotros para hacer crecer su negocio de IA.',
    aiApps: 'Aplicaciones de IA',
    monthlyVisits: 'Visitas Mensuales',
    freeDirectory: 'Directorio Gratuito #1',
    footerDescription: 'El directorio de herramientas gratuitas de IA más grande del mundo. Descubre y compara las mejores soluciones.',
    topCategories: 'Principales Categorías',
    quickLinks: 'Enlaces Rápidos',
    legalInfo: 'Información Legal',
    allRightsReserved: 'Todos los derechos reservados.',
    
    // Tool Detail Page Translations
    overviewOf: 'Descripción General de',
    prosAndConsOf: 'Pros y Contras de',
    pros: 'Pros',
    cons: 'Contras',
    readyToTry: '¿Listo para probar',
    getStartedFree: 'Empezar Gratis',
    pricingModel: 'Modelo de Precios',
    globalRating: 'Calificación Global',
    lastUpdated: 'Última Actualización',
    similarAiTools: 'Herramientas de IA Similares',
    classification: 'Clasificación',
    mainCategories: 'Categorías Principales',
    relatedTopics: 'Temas Relacionados',
    userReviews: 'Reseñas de Usuarios',
    faqTitle: 'Preguntas Frecuentes',
    reviews: 'reseñas',
    keyBenefits: 'Beneficios y Características Clave',
    backToTools: 'Volver a Herramientas',
    home: 'Inicio',
    tools: 'Herramientas',
  },
  fr: {
    browseTools: 'Parcourir les Outils',
    categories: 'Catégories',
    blogs: 'Blogs',
    myDashboard: 'Mon Tableau de Bord',
    admin: 'Admin',
    submitTool: 'Soumettre un Outil',
    signIn: 'Se Connecter',
    searchPlaceholder: 'Rechercher parmi 700+ outils IA...',
    searchBtn: 'Rechercher',
    allCategories: 'Toutes les Catégories',
    trending: 'Tendances',
    newest: 'Plus Récents',
    topRated: 'Mieux Notés',
    popular: 'Populaires',
    heroBadge: 'Rejoignez 50 000+ utilisateurs qui découvrent des outils IA',
    heroTitlePrefix: 'Le Répertoire Ultime des',
    heroTitleSuffix: 'Outils d\'IA',
    heroSubtitle: 'Recherchez parmi 700+ outils IA vérifiés par catégorie. Trouvez le logiciel parfait pour vos besoins.',
    exploreAllTools: 'Explorer Tous les Outils',
    submitYourProject: 'Soumettre Votre Projet',
    featuredInnovation: 'Innovations En Vedette',
    featuredSubtitle: 'Excellence en IA sélectionnée par nos experts',
    viewAllExcellence: 'Voir Tout',
    hyperGrowthTools: 'Outils à Forte Croissance',
    trendingSubtitle: 'Les solutions IA les plus recherchées de la semaine',
    seeTrends: 'Voir les Tendances',
    discoverByIntent: 'Découvrir par Catégorie',
    intentSubtitle: 'Chaque outil organisé pour votre flux de travail',
    exploreAllCategories: 'Explorer Toutes les Catégories',
    freshArrivals: 'Nouveautés du Moment',
    arrivalsSubtitle: 'Les derniers outils IA arrivés dans notre communauté',
    recentArrivals: 'Arrivées Récentes',
    featureYourProduct: 'Mettez en Avant Votre Produit IA',
    ctaSubtitle: 'Rejoignez des milliers de fondateurs qui nous font confiance.',
    aiApps: 'Applications IA',
    monthlyVisits: 'Visites Mensuelles',
    freeDirectory: 'Répertoire Gratuit n°1',
    footerDescription: 'Le plus grand répertoire d\'outils IA gratuits au monde. Découvrez et comparez les meilleures solutions IA.',
    topCategories: 'Meilleures Catégories',
    quickLinks: 'Liens Rapides',
    legalInfo: 'Informations Légales',
    allRightsReserved: 'Tous droits réservés.',
    
    // Tool Detail Page Translations
    overviewOf: 'Aperçu de',
    prosAndConsOf: 'Avantages et Inconvénients de',
    pros: 'Avantages',
    cons: 'Inconvénients',
    readyToTry: 'Prêt à essayer',
    getStartedFree: 'Commencer Gratuitement',
    pricingModel: 'Modèle de Prix',
    globalRating: 'Note Globale',
    lastUpdated: 'Dernière Mise à Jour',
    similarAiTools: 'Outils IA Similaires',
    classification: 'Classification',
    mainCategories: 'Catégories Principales',
    relatedTopics: 'Sujets Connexes',
    userReviews: 'Avis Utilisateurs',
    faqTitle: 'Foire Aux Questions',
    reviews: 'avis',
    keyBenefits: 'Avantages et Fonctionnalités Clés',
    backToTools: 'Retour aux Outils',
    home: 'Accueil',
    tools: 'Outils',
  },
  de: {
    browseTools: 'Tools Durchsuchen',
    categories: 'Kategorien',
    blogs: 'Blogs',
    myDashboard: 'Mein Dashboard',
    admin: 'Admin',
    submitTool: 'Tool Einreichen',
    signIn: 'Anmelden',
    searchPlaceholder: 'Über 700+ KI-Tools suchen...',
    searchBtn: 'Suchen',
    allCategories: 'Alle Kategorien',
    trending: 'Trends',
    newest: 'Neueste',
    topRated: 'Am Besten Bewertet',
    popular: 'Beliebt',
    heroBadge: 'Schließen Sie sich 50.000+ Nutzern an, die KI-Tools entdecken',
    heroTitlePrefix: 'Das Ultimative Verzeichnis für',
    heroTitleSuffix: 'KI-Werkzeuge',
    heroSubtitle: 'Suchen Sie über 700+ verifizierte KI-Tools nach Kategorie. Finden Sie die perfekte Software.',
    exploreAllTools: 'Alle Tools Erkunden',
    submitYourProject: 'Projekt Einreichen',
    featuredInnovation: 'Hervorgehobene Innovationen',
    featuredSubtitle: 'Von unseren Experten empfohlene Spitzen-KI',
    viewAllExcellence: 'Alle Anzeigen',
    hyperGrowthTools: 'Wachstumsstarke KI-Tools',
    trendingSubtitle: 'Die meistgesuchten KI-Lösungen dieser Woche',
    seeTrends: 'Trends Ansehen',
    discoverByIntent: 'Nach Kategorie Entdecken',
    intentSubtitle: 'Alle Werkzeuge professionell für Ihren Workflow organisiert',
    exploreAllCategories: 'Alle Kategorien Erkunden',
    freshArrivals: 'Neu Eingetroffen',
    arrivalsSubtitle: 'Die neuesten KI-Zugänge unserer Community',
    recentArrivals: 'Neueste Zugänge',
    featureYourProduct: 'Präsentieren Sie Ihr KI-Produkt',
    ctaSubtitle: 'Schließen Sie sich Tausenden von Gründern an.',
    aiApps: 'KI-Anwendungen',
    monthlyVisits: 'Monatliche Besuche',
    freeDirectory: 'Nr. 1 Kostenloses Verzeichnis',
    footerDescription: 'Das weltweit größte Verzeichnis für kostenlose KI-Tools. Entdecken und vergleichen Sie die besten KI-Lösungen.',
    topCategories: 'Top-Kategorien',
    quickLinks: 'Schnelllinks',
    legalInfo: 'Rechtliches & Info',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    
    // Tool Detail Page Translations
    overviewOf: 'Übersicht über',
    prosAndConsOf: 'Vor- und Nachteile von',
    pros: 'Vorteile',
    cons: 'Nachteile',
    readyToTry: 'Bereit auszuprobieren',
    getStartedFree: 'Kostenlos Starten',
    pricingModel: 'Preismodell',
    globalRating: 'Gesamtbewertung',
    lastUpdated: 'Zuletzt Aktualisiert',
    similarAiTools: 'Ähnliche KI-Tools',
    classification: 'Klassifizierung',
    mainCategories: 'Hauptkategorien',
    relatedTopics: 'Verwandte Themen',
    userReviews: 'Nutzerbewertungen',
    faqTitle: 'Häufig Gestellte Fragen',
    reviews: 'Bewertungen',
    keyBenefits: 'Wichtigste Vorteile & Funktionen',
    backToTools: 'Zurück zu Tools',
    home: 'Startseite',
    tools: 'Tools',
  },
  pt: {
    browseTools: 'Navegar por Ferramentas',
    categories: 'Categorias',
    blogs: 'Blogs',
    myDashboard: 'Meu Painel',
    admin: 'Admin',
    submitTool: 'Enviar Ferramenta',
    signIn: 'Entrar',
    searchPlaceholder: 'Pesquisar +700 ferramentas de IA...',
    searchBtn: 'Buscar',
    allCategories: 'Todas as Categorias',
    trending: 'Em Alta',
    newest: 'Mais Recentes',
    topRated: 'Mais Avaliadas',
    popular: 'Populares',
    heroBadge: 'Junte-se a mais de 50.000 usuários descobrindo ferramentas de IA',
    heroTitlePrefix: 'O Diretório Definitivo de',
    heroTitleSuffix: 'Ferramentas de IA',
    heroSubtitle: 'Pesquise mais de 700 ferramentas de IA verificadas por categoria. Encontre a solução ideal.',
    exploreAllTools: 'Explorar Todas as Ferramentas',
    submitYourProject: 'Enviar Seu Projeto',
    featuredInnovation: 'Inovação em Destaque',
    featuredSubtitle: 'Excelência em IA selecionada pelos nossos especialistas',
    viewAllExcellence: 'Ver Todas',
    hyperGrowthTools: 'Ferramentas em Alto Crescimento',
    trendingSubtitle: 'As soluções de IA mais buscadas da semana',
    seeTrends: 'Ver Tendências',
    discoverByIntent: 'Descobrir por Categoria',
    intentSubtitle: 'Todas as ferramentas organizadas para seu fluxo de trabalho',
    exploreAllCategories: 'Explorar Todas as Categorias',
    freshArrivals: 'Novidades Recentes',
    arrivalsSubtitle: 'As últimas novidades de IA na nossa comunidade',
    recentArrivals: 'Chegadas Recentes',
    featureYourProduct: 'Destaque Seu Produto de IA',
    ctaSubtitle: 'Junte-se a milhares de criadores que confiam em nós.',
    aiApps: 'Aplicativos de IA',
    monthlyVisits: 'Visitas Mensais',
    freeDirectory: 'Diretório Gratuito #1',
    footerDescription: 'O maior diretório do mundo de ferramentas gratuitas de IA. Descubra e compare as melhores soluções.',
    topCategories: 'Principais Categorias',
    quickLinks: 'Links Rápidos',
    legalInfo: 'Informações Legais',
    allRightsReserved: 'Todos os direitos reservados.',
    
    // Tool Detail Page Translations
    overviewOf: 'Visão Geral de',
    prosAndConsOf: 'Prós e Contras de',
    pros: 'Prós',
    cons: 'Contras',
    readyToTry: 'Pronto para experimentar',
    getStartedFree: 'Começar Grátis',
    pricingModel: 'Modelo de Preço',
    globalRating: 'Avaliação Global',
    lastUpdated: 'Última Atualização',
    similarAiTools: 'Ferramentas de IA Semelhantes',
    classification: 'Classificação',
    mainCategories: 'Categorias Principais',
    relatedTopics: 'Tópicos Relacionados',
    userReviews: 'Avaliações de Usuários',
    faqTitle: 'Perguntas Frequentes',
    reviews: 'avaliações',
    keyBenefits: 'Principais Benefícios e Recursos',
    backToTools: 'Voltar para Ferramentas',
    home: 'Início',
    tools: 'Ferramentas',
  },
  ar: {
    browseTools: 'تصفح الأدوات',
    categories: 'الفئات',
    blogs: 'المدونات',
    myDashboard: 'لوحة التحكم',
    admin: 'الإدارة',
    submitTool: 'إضافة أداة',
    signIn: 'تسجيل الدخول',
    searchPlaceholder: 'ابحث في أكثر من 700 أداة ذكاء اصطناعي...',
    searchBtn: 'بحث',
    allCategories: 'جميع الفئات',
    trending: 'الأكثر رواجاً',
    newest: 'الأحدث',
    topRated: 'الأعلى تقييماً',
    popular: 'الأكثر شعبية',
    heroBadge: 'انضم إلى أكثر من 50,000 مستخدم يكتشفون أدوات الذكاء الاصطناعي',
    heroTitlePrefix: 'الدليل الشامل لـ',
    heroTitleSuffix: 'أدوات الذكاء الاصطناعي',
    heroSubtitle: 'ابحث في أكثر من 700 أداة ذكاء اصطناعي موثوقة حسب الفئة. اعثر على البرامج المثالية لأعمالك.',
    exploreAllTools: 'استكشف جميع الأدوات',
    submitYourProject: 'أضف مشروعك',
    featuredInnovation: 'ابتكارات مميزة',
    featuredSubtitle: 'أفضل أدوات الذكاء الاصطناعي المختارة من قبل خبرائنا',
    viewAllExcellence: 'عرض الكل',
    hyperGrowthTools: 'أدوات سريعة النمو',
    trendingSubtitle: 'حلول الذكاء الاصطناعي الأكثر بحثاً هذا الأسبوع',
    seeTrends: 'عرض الاتجاهات',
    discoverByIntent: 'استكشف حسب المجال',
    intentSubtitle: 'كل أداة تحتاجها منظمة باحترافية لسير عملك',
    exploreAllCategories: 'استكشف جميع الفئات',
    freshArrivals: 'أحدث الإضافات',
    arrivalsSubtitle: 'أحدث أدوات الذكاء الاصطناعي المنضمة لمجتمعنا',
    recentArrivals: 'الواصلة حديثاً',
    featureYourProduct: 'اميز منتجك من الذكاء الاصطناعي',
    ctaSubtitle: 'انضم إلى آلاف المؤسسين الذين يثقون بنا لتنمية مشاريعهم.',
    aiApps: 'تطبيقات ذكاء اصطناعي',
    monthlyVisits: 'زيارة شهرية',
    freeDirectory: 'الدليل المجاني الأول',
    footerDescription: 'أكبر دليل مجاني لأدوات الذكاء الاصطناعي في العالم. اكتشف وقارن أفضل حلول الذكاء الاصطناعي.',
    topCategories: 'أهم الفئات',
    quickLinks: 'روابط سريعة',
    legalInfo: 'معلومات قانونية',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    
    // Tool Detail Page Translations
    overviewOf: 'نظرة عامة على',
    prosAndConsOf: 'إيجابيات وسلبيات',
    pros: 'الإيجابيات',
    cons: 'السلبيات',
    readyToTry: 'جاهز لتجربة',
    getStartedFree: 'ابدأ مجاناً',
    pricingModel: 'نموذج التسعير',
    globalRating: 'التقييم العام',
    lastUpdated: 'آخر تحديث',
    similarAiTools: 'أدوات ذكاء اصطناعي مشابهة',
    classification: 'التصنيف',
    mainCategories: 'الفئات الرئيسية',
    relatedTopics: 'مواضيع ذات صلة',
    userReviews: 'تقييمات المستخدمين',
    faqTitle: 'الأسئلة الشائعة',
    reviews: 'تقييمات',
    keyBenefits: 'الميزات والفوائد الرئيسية',
    backToTools: 'العودة للأدوات',
    home: 'الرئيسية',
    tools: 'الأدوات',
  },
  ru: {
    browseTools: 'Каталог Инструментов',
    categories: 'Категории',
    blogs: 'Блоги',
    myDashboard: 'Панель Управления',
    admin: 'Админ',
    submitTool: 'Добавить Инструмент',
    signIn: 'Войти',
    searchPlaceholder: 'Поиск по 700+ ИИ-инструментам...',
    searchBtn: 'Поиск',
    allCategories: 'Все Категории',
    trending: 'В Тренде',
    newest: 'Новые',
    topRated: 'Лучшие',
    popular: 'Популярные',
    heroBadge: 'Присоединяйтесь к 50 000+ пользователей ИИ-инструментов',
    heroTitlePrefix: 'Главный Каталог',
    heroTitleSuffix: 'Инструментов ИИ',
    heroSubtitle: 'Поиск по 700+ проверенным ИИ-сервисам по категориям. Найдите идеальное решение для бизнеса.',
    exploreAllTools: 'Смотреть Все Сервисы',
    submitYourProject: 'Добавить Свой Проект',
    featuredInnovation: 'Рекомендуемые Инновации',
    featuredSubtitle: 'Отобранные экспертами лучшие ИИ-решения',
    viewAllExcellence: 'Смотреть Все',
    hyperGrowthTools: 'Быстрорастущие Сервисы',
    trendingSubtitle: 'Самые популярные ИИ-инструменты этой недели',
    seeTrends: 'Смотреть Тренды',
    discoverByIntent: 'Поиск по Категориям',
    intentSubtitle: 'Все нужные инструменты, организованные для вашей работы',
    exploreAllCategories: 'Смотреть Все Категории',
    freshArrivals: 'Свежие Поступления',
    arrivalsSubtitle: 'Новейшие ИИ-сервисы в нашем сообществе',
    recentArrivals: 'Новые Поступления',
    featureYourProduct: 'Разместите Свой ИИ-Продукт',
    ctaSubtitle: 'Присоединяйтесь к тысячам основателей.',
    aiApps: 'ИИ-Приложений',
    monthlyVisits: 'Визитов в Месяц',
    freeDirectory: 'Бесплатный Каталог №1',
    footerDescription: 'Крупнейший в мире каталог бесплатных инструментов ИИ. Находите и сравнивайте лучшие решения.',
    topCategories: 'Популярные Категории',
    quickLinks: 'Быстрые Ссылки',
    legalInfo: 'Правовая Информация',
    allRightsReserved: 'Все права защищены.',
    
    // Tool Detail Page Translations
    overviewOf: 'Обзор',
    prosAndConsOf: 'Плюсы и Минусы',
    pros: 'Плюсы',
    cons: 'Минусы',
    readyToTry: 'Готовы попробовать',
    getStartedFree: 'Начать Бесплатно',
    pricingModel: 'Модель Оплаты',
    globalRating: 'Общий Рейтинг',
    lastUpdated: 'Последнее Обновление',
    similarAiTools: 'Похожие ИИ-Сервисы',
    classification: 'Классификация',
    mainCategories: 'Основные Категории',
    relatedTopics: 'Похожие Темы',
    userReviews: 'Отзывы Пользователей',
    faqTitle: 'Часто Задаваемые Вопросы',
    reviews: 'отзывов',
    keyBenefits: 'Ключевые Преимущества и Функции',
    backToTools: 'Назад к Каталогу',
    home: 'Главная',
    tools: 'Инструменты',
  },
  ja: {
    browseTools: 'ツールを探す',
    categories: 'カテゴリ',
    blogs: 'ブログ',
    myDashboard: 'ダッシュボード',
    admin: '管理者',
    submitTool: 'ツールを投稿',
    signIn: 'ログイン',
    searchPlaceholder: '700以上のAIツールを検索...',
    searchBtn: '検索',
    allCategories: 'すべてのカテゴリ',
    trending: 'トレンド',
    newest: '新着',
    topRated: '高評価',
    popular: '人気',
    heroBadge: '50,000人以上のユーザーが新しいAIツールを発見中',
    heroTitlePrefix: '究極の',
    heroTitleSuffix: 'AIツールディレクトリ',
    heroSubtitle: '700以上の検証済みAIツールをカテゴリ別に検索。あなたのビジネスに最適なツールを見つけましょう。',
    exploreAllTools: 'すべてのツールを見る',
    submitYourProject: 'プロジェクトを掲載する',
    featuredInnovation: '注目のイノベーション',
    featuredSubtitle: '専門家が厳選した優秀なAIツール',
    viewAllExcellence: 'すべて表示',
    hyperGrowthTools: '急成長中のAIツール',
    trendingSubtitle: '今週最も検索されたAIソリューション',
    seeTrends: 'トレンドを見る',
    discoverByIntent: '目的別に探す',
    intentSubtitle: 'あなたのワークフローに合わせて整理されたツール群',
    exploreAllCategories: 'すべてのカテゴリを見る',
    freshArrivals: '新着AIツール',
    arrivalsSubtitle: 'コミュニティに最近追加された最新のAIツール',
    recentArrivals: '最近の追加',
    featureYourProduct: 'あなたのAI製品を掲載しませんか？',
    ctaSubtitle: '数千人の創業者と一緒にあなたのAIビジネスを成長させましょう。',
    aiApps: 'AIアプリ数',
    monthlyVisits: '月間訪問数',
    freeDirectory: 'No.1 無料ディレクトリ',
    footerDescription: '世界最大の無料AIツールディレクトリ。最高の人工知能ソリューションを発見・比較できます。',
    topCategories: '人気カテゴリ',
    quickLinks: 'クイックリンク',
    legalInfo: '法的情報',
    allRightsReserved: 'All rights reserved.',
    
    // Tool Detail Page Translations
    overviewOf: '概要:',
    prosAndConsOf: '長所と短所:',
    pros: '長所',
    cons: '短所',
    readyToTry: '試してみますか？',
    getStartedFree: '無料で始める',
    pricingModel: '料金体系',
    globalRating: '総合評価',
    lastUpdated: '最終更新日',
    similarAiTools: '類似のAIツール',
    classification: '分類',
    mainCategories: 'メインカテゴリ',
    relatedTopics: '関連トピック',
    userReviews: 'ユーザーレビュー',
    faqTitle: 'よくある質問',
    reviews: '件のレビュー',
    keyBenefits: '主な特徴とメリット',
    backToTools: 'ツール一覧に戻る',
    home: 'ホーム',
    tools: 'ツール',
  },
  zh: {
    browseTools: '浏览 AI 工具',
    categories: '工具分类',
    blogs: '博客文章',
    myDashboard: '个人中心',
    admin: '管理后台',
    submitTool: '提交 AI 工具',
    signIn: '登录',
    searchPlaceholder: '搜索 700+ 款 AI 工具...',
    searchBtn: '搜索',
    allCategories: '全部分类',
    trending: '热门趋势',
    newest: '最新发布',
    topRated: '最高好评',
    popular: '最受欢迎',
    heroBadge: '加入 50,000+ 用户的 AI 工具探索社区',
    heroTitlePrefix: '终极',
    heroTitleSuffix: 'AI 工具导航目录',
    heroSubtitle: '按分类搜索 700+ 款已验证的 AI 工具。为您的业务找到最完美的人工智能软件。',
    exploreAllTools: '探索所有工具',
    submitYourProject: '提交您的 AI 项目',
    featuredInnovation: '精选创新工具',
    featuredSubtitle: '专家团队精心挑选的顶级 AI 解决方案',
    viewAllExcellence: '查看全部',
    hyperGrowthTools: '高速增长工具',
    trendingSubtitle: '本周搜索量最高的 AI 工具',
    seeTrends: '查看趋势',
    discoverByIntent: '按使用需求探索',
    intentSubtitle: '专业分类整理，满足您工作流的每一项需求',
    exploreAllCategories: '探索所有分类',
    freshArrivals: '最新上架',
    arrivalsSubtitle: '社区最新收录的 AI 工具',
    recentArrivals: '最新收录',
    featureYourProduct: '推广您的 AI 产品',
    ctaSubtitle: '加入数千名创始人的行列，推广您的 AI 业务。',
    aiApps: 'AI 工具总数',
    monthlyVisits: '月访问量',
    freeDirectory: '#1 免费 AI 目录',
    footerDescription: '全球最大的免费 AI 工具目录。探索并比较最顶尖的人工智能解决方案。',
    topCategories: '热门分类',
    quickLinks: '快速链接',
    legalInfo: '法律条款',
    allRightsReserved: '保留所有权利。',
    
    // Tool Detail Page Translations
    overviewOf: '概述：',
    prosAndConsOf: '优缺点：',
    pros: '优点',
    cons: '缺点',
    readyToTry: '准备尝试',
    getStartedFree: '免费开始使用',
    pricingModel: '定价模式',
    globalRating: '综合评分',
    lastUpdated: '最后更新',
    similarAiTools: '相似 AI 工具',
    classification: '分类',
    mainCategories: '主要分类',
    relatedTopics: '相关主题',
    userReviews: '用户评价',
    faqTitle: '常见问题集',
    reviews: '条评价',
    keyBenefits: '核心功能与优势',
    backToTools: '返回工具列表',
    home: '首页',
    tools: '工具',
  },
  it: {
    browseTools: 'Esplora Strumenti',
    categories: 'Categorie',
    blogs: 'Blog',
    myDashboard: 'La Mia Dashboard',
    admin: 'Admin',
    submitTool: 'Invia Strumento',
    signIn: 'Accedi',
    searchPlaceholder: 'Cerca tra oltre 700 strumenti IA...',
    searchBtn: 'Cerca',
    allCategories: 'Tutte le Categorie',
    trending: 'In Tendenza',
    newest: 'Più Recenti',
    topRated: 'I Più Votati',
    popular: 'Popolari',
    heroBadge: 'Unisciti a oltre 50.000 utenti che scoprono strumenti IA',
    heroTitlePrefix: 'La Directory Definitiva di',
    heroTitleSuffix: 'Strumenti IA',
    heroSubtitle: 'Cerca oltre 700 strumenti IA verificati per categoria. Trova il software perfetto per il tuo business.',
    exploreAllTools: 'Esplora Tutti i Tool',
    submitYourProject: 'Invia il Tuo Progetto',
    featuredInnovation: 'Innovazioni In Evidenza',
    featuredSubtitle: 'Eccellenza IA selezionata dai nostri esperti',
    viewAllExcellence: 'Vedi Tutti',
    hyperGrowthTools: 'Strumenti in Forte Crescita',
    trendingSubtitle: 'Le soluzioni IA più cercate della settimana',
    seeTrends: 'Vedi Tendenze',
    discoverByIntent: 'Scopri per Categoria',
    intentSubtitle: 'Ogni strumento organizzato per il tuo flusso di lavoro',
    exploreAllCategories: 'Esplora Tutte le Categorie',
    freshArrivals: 'Ultime Novità',
    arrivalsSubtitle: 'I più recenti strumenti IA arrivati nella community',
    recentArrivals: 'Arrivi Recenti',
    featureYourProduct: 'Promuovi il Tuo Prodotto IA',
    ctaSubtitle: 'Unisciti a migliaia di creatori.',
    aiApps: 'App IA',
    monthlyVisits: 'Visite Mensili',
    freeDirectory: 'Directory Gratuita n. 1',
    footerDescription: 'La più grande directory al mondo di strumenti IA gratuiti. Scopri e confronta le migliori soluzioni.',
    topCategories: 'Categorie Principali',
    quickLinks: 'Link Rapidi',
    legalInfo: 'Info Legali',
    allRightsReserved: 'Tutti i diritti riservati.',
    
    // Tool Detail Page Translations
    overviewOf: 'Panoramica di',
    prosAndConsOf: 'Pro e Contro di',
    pros: 'Pro',
    cons: 'Contro',
    readyToTry: 'Pronto a provare',
    getStartedFree: 'Inizia Gratis',
    pricingModel: 'Modello di Prezzo',
    globalRating: 'Valutazione Globale',
    lastUpdated: 'Ultimo Aggiornamento',
    similarAiTools: 'Strumenti IA Simili',
    classification: 'Classificazione',
    mainCategories: 'Categorie Principali',
    relatedTopics: 'Argomenti Correlati',
    userReviews: 'Recensioni Utenti',
    faqTitle: 'Domande Frequenti',
    reviews: 'recensioni',
    keyBenefits: 'Principali Vantaggi e Funzionalità',
    backToTools: 'Torna agli Strumenti',
    home: 'Home',
    tools: 'Strumenti',
  },
  nl: {
    browseTools: 'Tools Bladeren',
    categories: 'Categorieën',
    blogs: 'Blogs',
    myDashboard: 'Mijn Dashboard',
    admin: 'Admin',
    submitTool: 'Tool Inzenden',
    signIn: 'Inloggen',
    searchPlaceholder: 'Zoek in 700+ AI-tools...',
    searchBtn: 'Zoeken',
    allCategories: 'Alle Categorieën',
    trending: 'Populair',
    newest: 'Nieuwste',
    topRated: 'Best Beoordeeld',
    popular: 'Favoriet',
    heroBadge: 'Sluit je aan bij 50.000+ gebruikers die AI-tools ontdekken',
    heroTitlePrefix: 'De Ultieme',
    heroTitleSuffix: 'AI Tools Gids',
    heroSubtitle: 'Zoek in 700+ geverifieerde AI-tools per categorie. Vind de perfecte AI-software voor jouw bedrijf.',
    exploreAllTools: 'Ontdek Alle Tools',
    submitYourProject: 'Stuur Je Project In',
    featuredInnovation: 'Uitgelichte Innovatie',
    featuredSubtitle: 'Geselecteerde AI-kwaliteit aanbevolen door onze experts',
    viewAllExcellence: 'Bekijk Alles',
    hyperGrowthTools: 'Snelgroeiende AI Tools',
    trendingSubtitle: 'De meest gezochte AI-oplossingen van deze week',
    seeTrends: 'Bekijk Trends',
    discoverByIntent: 'Ontdek per Categorie',
    intentSubtitle: 'Elke tool georganiseerd voor jouw workflow',
    exploreAllCategories: 'Ontdek Alle Categorieën',
    freshArrivals: 'Vers Van De Pers',
    arrivalsSubtitle: 'Nieuwste AI-toevoegingen in onze community',
    recentArrivals: 'Recente Toevoegingen',
    featureYourProduct: 'Promoot Jouw AI-Product',
    ctaSubtitle: 'Sluit je aan bij duizenden oprichters.',
    aiApps: 'AI Apps',
    monthlyVisits: 'Maandelijkse Bezoeken',
    freeDirectory: '#1 Gratis Gids',
    footerDescription: 'Word\'s grootste gids voor gratis AI-tools. Ontdek en vergelijk de beste kunstmatige intelligentie oplossingen.',
    topCategories: 'Top Categorieën',
    quickLinks: 'Snelle Links',
    legalInfo: 'Juridische Info',
    allRightsReserved: 'Alle rechten voorbehouden.',
    
    // Tool Detail Page Translations
    overviewOf: 'Overzicht van',
    prosAndConsOf: 'Voor- en Nadelen van',
    pros: 'Voordelen',
    cons: 'Nadelen',
    readyToTry: 'Klaar om te proberen',
    getStartedFree: 'Gratis Beginnen',
    pricingModel: 'Prijsmodel',
    globalRating: 'Globale Beoordeling',
    lastUpdated: 'Laatst Bijgewerkt',
    similarAiTools: 'Vergelijkbare AI Tools',
    classification: 'Classificatie',
    mainCategories: 'Hoofdcategorieën',
    relatedTopics: 'Gerelateerde Onderwerpen',
    userReviews: 'Gebruikersbeoordelingen',
    faqTitle: 'Veelgestelde Vragen',
    reviews: 'beoordelingen',
    keyBenefits: 'Belangrijkste Voordelen & Functies',
    backToTools: 'Terug naar Tools',
    home: 'Home',
    tools: 'Tools',
  },
};
