/**
 * Centralized configuration for BestAIToolsFree PDF Suite.
 * Defines metadata, routes, limits, feature flags, and categories.
 */

export const PDF_CONFIG = {
  maxFileSizeBytes: 100 * 1024 * 1024, // 100MB client-side limit
  maxPageCount: 500, // Sensible page ceiling for browser rendering
  defaultRenderScale: 1.5, // Standard resolution
  scales: {
    standard: 1.5,
    high: 2.0,
    veryHigh: 3.0,
  },
};

export const PDF_CATEGORIES = [
  { id: 'organize', label: 'Organize PDFs', description: 'Merge, split, rotate, unlock, and manage PDF pages' },
  { id: 'convert', label: 'Convert PDFs', description: 'Convert between PDF and Word, PowerPoint, Excel, or images' },
  { id: 'edit', label: 'Edit & Annotate', description: 'Add text, draw, insert shapes, and annotate PDF documents' },
  { id: 'optimize', label: 'Optimize', description: 'Reduce PDF file size in your browser' },
];

export const PDF_TOOLS = [
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    seoTitle: 'Merge PDF Online Free – Combine PDF Files | BestAIToolsFree',
    seoDescription: 'Merge multiple PDF files into one document online for free. Reorder files easily with drag & drop. Your files are processed directly in your browser.',
    category: 'organize',
    iconName: 'Files',
    tagline: 'Combine multiple PDF files in any order you choose',
    description: 'Combine multiple PDF documents into a single organized file with easy drag-and-drop file reordering. Free, fast, and processed locally on your device.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: true,
    status: 'live',
    popular: true,
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    seoTitle: 'Split PDF Online Free – Extract PDF Pages | BestAIToolsFree',
    seoDescription: 'Split PDF files by page ranges or extract individual pages online for free. Visual page selection and instant browser-side processing.',
    category: 'organize',
    iconName: 'Scissors',
    tagline: 'Extract specific pages or split into individual PDF documents',
    description: 'Extract custom page ranges (e.g., 1-3, 5) or burst an entire PDF into individual single-page documents without server uploads.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    seoTitle: 'Rotate PDF Online Free – Rotate PDF Pages Permanently | BestAIToolsFree',
    seoDescription: 'Rotate individual pages or entire PDF files 90, 180, or 270 degrees online for free. Visual thumbnail preview with instant in-browser export.',
    category: 'organize',
    iconName: 'RotateCw',
    tagline: 'Rotate individual pages or entire PDF documents permanently',
    description: 'Rotate sideways or upside-down PDF pages by 90°, 180°, or 270°. Preview pages visually and save permanently to your device.',
    badge: 'Organize',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'delete-pages',
    name: 'Delete PDF Pages',
    seoTitle: 'Delete PDF Pages Online Free – Remove Pages from PDF | BestAIToolsFree',
    seoDescription: 'Delete unwanted pages from any PDF document online for free. Visual thumbnail grid with multi-page selection and instant export.',
    category: 'organize',
    iconName: 'Trash2',
    tagline: 'Remove unwanted pages from PDF files with live preview',
    description: 'Select and delete specific pages from any PDF file. View visual page thumbnails, select unwanted pages, and download the cleaned document.',
    badge: 'Organize',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    seoTitle: 'JPG to PDF Online Free – Convert Images to PDF | BestAIToolsFree',
    seoDescription: 'Convert JPG images into a single PDF document online for free. Custom page orientation, margins, and page sizes with zero server uploads.',
    category: 'convert',
    iconName: 'FileText',
    tagline: 'Convert single or multiple JPG images into a formatted PDF',
    description: 'Combine multiple JPG photos into a clean PDF file with custom page sizing (A4, Letter, Fit to Image), margin controls, and orientation.',
    badge: 'Converter',
    accepts: ['.jpg', '.jpeg', 'image/jpeg'],
    multiple: true,
    status: 'live',
    popular: true,
  },
  {
    slug: 'png-to-pdf',
    name: 'PNG to PDF',
    seoTitle: 'PNG to PDF Online Free – Convert PNG Images to PDF | BestAIToolsFree',
    seoDescription: 'Convert PNG images with transparency into PDF files online for free. Multi-image batch support and customizable document layouts.',
    category: 'convert',
    iconName: 'Layers',
    tagline: 'Convert PNG graphics and screenshots into clean PDF files',
    description: 'Convert PNG images into formatted PDF documents while preserving color clarity and transparency. Reorder images and configure page layout.',
    badge: 'Converter',
    accepts: ['.png', 'image/png'],
    multiple: true,
    status: 'live',
    popular: false,
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    seoTitle: 'PDF to JPG Online Free – Convert PDF Pages to JPG | BestAIToolsFree',
    seoDescription: 'Convert PDF pages to high-resolution JPG images online for free. Download individual page images or all pages as a single ZIP archive.',
    category: 'convert',
    iconName: 'Image',
    tagline: 'High-quality PDF page rendering to JPG format',
    description: 'Render every page of your PDF into crisp JPG images. Choose resolution presets (Standard, High, Very High) and download as a ZIP.',
    badge: 'Converter',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'pdf-to-png',
    name: 'PDF to PNG',
    seoTitle: 'PDF to PNG Online Free – Convert PDF Pages to PNG | BestAIToolsFree',
    seoDescription: 'Convert PDF pages to lossless PNG images online for free. High-quality page rendering with selectable resolution and batch ZIP download.',
    category: 'convert',
    iconName: 'FileImage',
    tagline: 'Render PDF pages into crisp, lossless PNG images',
    description: 'Extract pages from PDF documents as sharp PNG images. Ideal for illustrations, graphs, presentations, and digital design workflows.',
    badge: 'Converter',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    seoTitle: 'Compress PDF Online Free – Reduce PDF File Size | BestAIToolsFree',
    seoDescription: 'Reduce PDF file size directly in your browser. Select from Gentle, Balanced, and Maximum compression presets. Processed locally with zero server uploads.',
    category: 'optimize',
    iconName: 'Minimize2',
    tagline: 'Reduce PDF file size using selectable browser compression presets',
    description: 'Optimize PDF structure and compress pages locally on your device using selectable presets with zero server uploads.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    seoTitle: 'Unlock PDF Online Free – Remove Password from PDF | BestAIToolsFree',
    seoDescription: 'Remove passwords and restrictions from PDF files online for free. Instantly unlock secured PDF documents so you can edit, print, and copy.',
    category: 'organize',
    iconName: 'Unlock',
    tagline: 'Remove PDF passwords and unlock protected documents',
    description: 'Remove user or owner passwords from your PDF documents safely. Unlock files so you can edit, print, copy, and manage them without restrictions.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    seoTitle: 'PDF to Word Online Free – Convert PDF to DOCX | BestAIToolsFree',
    seoDescription: 'Convert PDF documents into editable Word (.docx) files online for free. Extracts text and tables for easy editing. Files are deleted after conversion.',
    category: 'convert',
    iconName: 'FileText',
    tagline: 'Convert PDF files into editable DOCX Word documents',
    description: 'Convert supported PDF text and document structures into editable Microsoft Word (.docx) files with temporary file cleanup.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    seoTitle: 'PDF to PowerPoint Online Free – Convert PDF to PPTX | BestAIToolsFree',
    seoDescription: 'Convert PDF documents into editable PowerPoint (.pptx) presentations online for free. Preserves layout and slide graphics with temporary file cleanup.',
    category: 'convert',
    iconName: 'Presentation',
    tagline: 'Turn your PDF pages into PowerPoint slide decks',
    description: 'Convert every page of your PDF into presentation-ready PowerPoint slides for seamless pitching and lectures.',
    badge: 'Converter',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    seoTitle: 'PDF to Excel Online Free – Extract Tables to XLSX | BestAIToolsFree',
    seoDescription: 'Extract tabular data from PDF files into formatted Excel (.xlsx) spreadsheets online for free. Automatic table detection with zero permanent storage.',
    category: 'convert',
    iconName: 'Sheet',
    tagline: 'Extract tables from PDFs into Excel spreadsheets',
    description: 'Detect and extract tabular grids and data columns from PDF documents directly into cleanly formatted multi-sheet Excel files.',
    badge: 'Popular',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    seoTitle: 'Word to PDF Online Free – Convert DOCX to PDF | BestAIToolsFree',
    seoDescription: 'Make DOC and DOCX files easy to read and share by converting them to standard PDF documents online for free.',
    category: 'convert',
    iconName: 'FileCheck',
    tagline: 'Make DOC and DOCX files easy to share by converting them to PDF',
    description: 'Convert Microsoft Word documents (.docx, .doc) into standard PDF documents with consistent styling, headers, and pagination.',
    badge: 'Popular',
    accepts: ['.docx', '.doc', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
    multiple: false,
    status: 'live',
    popular: true,
  },
  {
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    seoTitle: 'PowerPoint to PDF Online Free – Convert PPTX to PDF | BestAIToolsFree',
    seoDescription: 'Make PPT and PPTX presentations easy to view and distribute by converting them to high-resolution PDF online for free.',
    category: 'convert',
    iconName: 'Presentation',
    tagline: 'Make PPT and PPTX slideshows easy to view by converting to PDF',
    description: 'Convert PowerPoint slide decks into multi-page PDFs for easy printing, emailing, and presentation sharing.',
    badge: 'Converter',
    accepts: ['.pptx', '.ppt', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.ms-powerpoint'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    seoTitle: 'Excel to PDF Online Free – Convert XLSX to PDF | BestAIToolsFree',
    seoDescription: 'Make Excel spreadsheets easy to read and print by converting them to clean, paginated PDF tables online for free.',
    category: 'convert',
    iconName: 'Sheet',
    tagline: 'Make EXCEL spreadsheets easy to read and print as PDF',
    description: 'Format and convert Excel workbooks (.xlsx, .xls) into crisp, printable PDF documents with header borders and styled cells.',
    badge: 'Converter',
    accepts: ['.xlsx', '.xls', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'],
    multiple: false,
    status: 'live',
    popular: false,
  },
  {
    slug: 'edit-pdf',
    name: 'Edit PDF',
    seoTitle: 'Edit PDF Online Free – Add Text, Draw, and Annotate PDF | BestAIToolsFree',
    seoDescription: 'Add text, draw, insert shapes, and freehand annotations on PDF documents online for free. 100% private in-browser editor.',
    category: 'edit',
    iconName: 'PenTool',
    tagline: 'Add text, drawings, highlights, and annotations to your PDF',
    description: 'Add text, images, shapes, or freehand annotations to a PDF document. Customize size, font, and color directly in your browser.',
    badge: 'Studio',
    accepts: ['.pdf', 'application/pdf'],
    multiple: false,
    status: 'live',
    popular: true,
  },
];

export const LIVE_PDF_TOOLS = PDF_TOOLS.filter((t) => t.status === 'live');
export const POPULAR_PDF_TOOLS = PDF_TOOLS.filter((t) => t.popular);

export function getPdfToolBySlug(slug) {
  return PDF_TOOLS.find((t) => t.slug === slug) || null;
}

export function getRelatedPdfTools(slug, limit = 4) {
  return LIVE_PDF_TOOLS.filter((t) => t.slug !== slug).slice(0, limit);
}
