import { v4 as uuidv4 } from 'uuid';

export const categories = [
  // Topic/Context Categories
  { _id: uuidv4(), name: 'AI Writers', slug: 'ai-writers', type: 'topic', description: 'AI-powered writing assistants', icon: '✍️' },
  { _id: uuidv4(), name: 'Customer Support', slug: 'customer-support', type: 'topic', description: 'AI tools for customer service', icon: '💬' },
  { _id: uuidv4(), name: 'Education', slug: 'education', type: 'topic', description: 'AI tools for learning', icon: '📚' },
  { _id: uuidv4(), name: 'Digital Marketing', slug: 'digital-marketing', type: 'topic', description: 'AI for marketing', icon: '📱' },
  { _id: uuidv4(), name: 'SEO', slug: 'seo', type: 'topic', description: 'Search engine optimization tools', icon: '🔍' },
  { _id: uuidv4(), name: 'Social Media', slug: 'social-media', type: 'topic', description: 'Social media management', icon: '📲' },
  { _id: uuidv4(), name: 'Productivity', slug: 'productivity', type: 'topic', description: 'Boost your productivity', icon: '⚡' },
  { _id: uuidv4(), name: 'Business', slug: 'business', type: 'topic', description: 'Business automation tools', icon: '💼' },
  { _id: uuidv4(), name: 'Designing', slug: 'designing', type: 'topic', description: 'Design and creative tools', icon: '🎨' },
  { _id: uuidv4(), name: 'Dev Tools', slug: 'dev-tools', type: 'topic', description: 'Developer tools and coding assistants', icon: '💻' },
  { _id: uuidv4(), name: 'Music', slug: 'music', type: 'topic', description: 'AI music generation', icon: '🎵' },
  { _id: uuidv4(), name: 'Healthcare', slug: 'healthcare', type: 'topic', description: 'Healthcare AI solutions', icon: '🏥' },
  
  // Task/Action Categories
  { _id: uuidv4(), name: 'Text To Image', slug: 'text-to-image', type: 'task', description: 'Generate images from text', icon: '🖼️' },
  { _id: uuidv4(), name: 'Image Editing', slug: 'image-editing', type: 'task', description: 'Edit and enhance images', icon: '🎭' },
  { _id: uuidv4(), name: 'Video Editing', slug: 'video-editing', type: 'task', description: 'AI video editing tools', icon: '🎬' },
  { _id: uuidv4(), name: 'Audio Editing', slug: 'audio-editing', type: 'task', description: 'Audio processing tools', icon: '🎧' },
  { _id: uuidv4(), name: 'Text To Speech', slug: 'text-to-speech', type: 'task', description: 'Convert text to speech', icon: '🗣️' },
  { _id: uuidv4(), name: 'Text To Video', slug: 'text-to-video', type: 'task', description: 'Generate videos from text', icon: '📹' },
  { _id: uuidv4(), name: 'Blog Content', slug: 'blog-content', type: 'task', description: 'Generate blog articles', icon: '📝' },
  { _id: uuidv4(), name: 'Copy Writing', slug: 'copy-writing', type: 'task', description: 'Marketing copy generation', icon: '📄' },
  { _id: uuidv4(), name: 'Logo Generator', slug: 'logo-generator', type: 'task', description: 'Create logos with AI', icon: '🎯' },
  { _id: uuidv4(), name: 'Paraphrase', slug: 'paraphrase', type: 'task', description: 'Rewrite and paraphrase text', icon: '🔄' },
  
  // Job Role Categories
  { _id: uuidv4(), name: 'Students', slug: 'students', type: 'role', description: 'Tools for students', icon: '🎓' },
  { _id: uuidv4(), name: 'UI/UX Designers', slug: 'ui-ux-designers', type: 'role', description: 'Design tools', icon: '🎨' },
  { _id: uuidv4(), name: 'Developers', slug: 'developers', type: 'role', description: 'Tools for developers', icon: '👨‍💻' },
  { _id: uuidv4(), name: 'Content Creators', slug: 'content-creators', type: 'role', description: 'Content creation tools', icon: '📸' },
];

export const tools = [
  {
    _id: uuidv4(),
    name: 'ChatGPT',
    slug: 'chatgpt',
    shortDescription: 'Conversational AI assistant by OpenAI',
    description: 'ChatGPT is a state-of-the-art conversational AI that can help with writing, coding, analysis, and much more. It uses advanced natural language processing to understand and respond to user queries.',
    website: 'https://chat.openai.com',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['ai-writers', 'productivity', 'dev-tools'],
    tags: ['chatbot', 'writing', 'coding', 'GPT-4'],
    pricing: 'Freemium',
    features: ['Natural language conversations', 'Code generation', 'Content writing', 'Problem solving'],
    rating: 4.8,
    votes: 320,
    status: 'approved',
    featured: true,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Midjourney',
    slug: 'midjourney',
    shortDescription: 'AI art generator creating stunning visuals',
    description: 'Midjourney is an independent research lab that produces an AI program that creates images from textual descriptions. Known for its artistic and dreamlike image generation capabilities.',
    website: 'https://www.midjourney.com',
    logo: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['text-to-image', 'designing'],
    tags: ['image generation', 'art', 'creative'],
    pricing: 'Paid',
    features: ['High-quality image generation', 'Artistic styles', 'Commercial use', 'Community features'],
    rating: 4.7,
    votes: 285,
    status: 'approved',
    featured: true,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    shortDescription: 'OpenAI\'s powerful image generation model',
    description: 'DALL-E 3 is OpenAI\'s latest image generation model that creates highly accurate and detailed images from text descriptions. Integrated with ChatGPT for seamless workflow.',
    website: 'https://openai.com/dall-e-3',
    logo: 'https://images.unsplash.com/photo-1686191128892-c15d6d39bcb3?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['text-to-image', 'designing'],
    tags: ['image generation', 'OpenAI', 'creative'],
    pricing: 'Paid',
    features: ['Text-to-image generation', 'High accuracy', 'Multiple styles', 'ChatGPT integration'],
    rating: 4.6,
    votes: 198,
    status: 'approved',
    featured: true,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    shortDescription: 'AI pair programmer for code completion',
    description: 'GitHub Copilot is an AI coding assistant that helps you write code faster by suggesting whole lines or entire functions as you type.',
    website: 'https://github.com/features/copilot',
    logo: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['dev-tools', 'productivity'],
    tags: ['coding', 'development', 'GitHub', 'autocomplete'],
    pricing: 'Paid',
    features: ['Code suggestions', 'Multi-language support', 'IDE integration', 'Context-aware'],
    rating: 4.5,
    votes: 167,
    status: 'approved',
    featured: true,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Jasper AI',
    slug: 'jasper-ai',
    shortDescription: 'AI content platform for marketing teams',
    description: 'Jasper is an AI writing assistant that helps marketing teams create high-quality content faster. Perfect for blog posts, social media, and marketing copy.',
    website: 'https://www.jasper.ai',
    logo: 'https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['ai-writers', 'blog-content', 'digital-marketing'],
    tags: ['content writing', 'marketing', 'blog'],
    pricing: 'Paid',
    features: ['Blog post generation', 'Marketing copy', 'Templates', 'SEO optimization'],
    rating: 4.4,
    votes: 145,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Notion AI',
    slug: 'notion-ai',
    shortDescription: 'AI-powered workspace and note-taking',
    description: 'Notion AI combines the power of AI with Notion\'s flexible workspace to help you write, brainstorm, and organize your ideas more efficiently.',
    website: 'https://www.notion.so/product/ai',
    logo: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['productivity', 'ai-writers'],
    tags: ['productivity', 'notes', 'workspace'],
    pricing: 'Freemium',
    features: ['AI writing assistant', 'Note organization', 'Templates', 'Collaboration'],
    rating: 4.6,
    votes: 187,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Grammarly',
    slug: 'grammarly',
    shortDescription: 'AI writing assistant for grammar and style',
    description: 'Grammarly uses AI to help you write clearly and confidently across all your apps and websites with advanced grammar checking and writing suggestions.',
    website: 'https://www.grammarly.com',
    logo: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['ai-writers', 'productivity'],
    tags: ['grammar', 'writing', 'editing'],
    pricing: 'Freemium',
    features: ['Grammar checking', 'Style suggestions', 'Plagiarism detection', 'Tone analysis'],
    rating: 4.5,
    votes: 231,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: false,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    shortDescription: 'AI voice generator and text-to-speech',
    description: 'ElevenLabs offers the most realistic and versatile AI speech software. Create natural-sounding voices for any purpose.',
    website: 'https://elevenlabs.io',
    logo: 'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['text-to-speech', 'audio-editing'],
    tags: ['voice generation', 'speech', 'audio'],
    pricing: 'Freemium',
    features: ['Realistic voices', 'Multiple languages', 'Voice cloning', 'API access'],
    rating: 4.7,
    votes: 156,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Canva AI',
    slug: 'canva-ai',
    shortDescription: 'AI-powered design platform',
    description: 'Canva\'s AI features help you create stunning designs with text-to-image generation, background removal, and smart design suggestions.',
    website: 'https://www.canva.com',
    logo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['designing', 'image-editing'],
    tags: ['design', 'graphics', 'editing'],
    pricing: 'Freemium',
    features: ['Text-to-image', 'Templates', 'Background removal', 'Brand kit'],
    rating: 4.6,
    votes: 289,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: false,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    shortDescription: 'AI-powered answer engine',
    description: 'Perplexity AI is an answer engine that delivers accurate answers to complex questions using large language models and search technology.',
    website: 'https://www.perplexity.ai',
    logo: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['productivity', 'education'],
    tags: ['search', 'research', 'AI'],
    pricing: 'Freemium',
    features: ['AI-powered search', 'Source citations', 'Follow-up questions', 'Pro search'],
    rating: 4.5,
    votes: 124,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Runway ML',
    slug: 'runway-ml',
    shortDescription: 'AI video editing and generation',
    description: 'Runway is an applied AI research company shaping the next era of art, entertainment and human creativity with powerful AI video tools.',
    website: 'https://runwayml.com',
    logo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['video-editing', 'text-to-video'],
    tags: ['video', 'AI generation', 'editing'],
    pricing: 'Freemium',
    features: ['Text-to-video', 'Video editing', 'Green screen', 'Motion tracking'],
    rating: 4.6,
    votes: 112,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: true,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
  {
    _id: uuidv4(),
    name: 'Copy.ai',
    slug: 'copy-ai',
    shortDescription: 'AI copywriting tool for marketing',
    description: 'Copy.ai is an AI-powered copywriter that generates high-quality marketing copy for your business in seconds.',
    website: 'https://www.copy.ai',
    logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=200&h=200&fit=crop',
    screenshots: [],
    categories: ['copy-writing', 'digital-marketing'],
    tags: ['copywriting', 'marketing', 'content'],
    pricing: 'Freemium',
    features: ['Marketing copy', 'Blog posts', 'Product descriptions', 'Social media'],
    rating: 4.4,
    votes: 178,
    status: 'approved',
    featured: false,
    sponsored: false,
    trending: false,
    submittedBy: 'admin',
    createdAt: new Date(),
  },
];