/**
 * Tool Registry — Single Source of Truth for BestAIToolsFree Image Tools.
 * Carefully curated without repetitive/redundant entries.
 */

export const IMAGE_TOOLS = [
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortName: 'Compress Images',
    tagline: 'TinyPNG-grade browser compression with zero quality loss',
    description: 'Compress JPG, PNG, and WebP images instantly in your browser. Reduce file size by up to 80% while preserving crisp visual quality.',
    badge: 'Popular',
    badgeVariant: 'primary',
    iconName: 'Zap',
    category: 'compression',
    status: 'live',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: null, // Same as input by default
    popular: true,
    features: ['Up to 80% size reduction', 'Lossless & lossy modes', 'Batch download as ZIP'],
  },
  {
    slug: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    shortName: 'JPG → PNG',
    tagline: 'Lossless conversion from JPEG to PNG format',
    description: 'Convert JPEG images into high-quality PNG format. Preserves original resolution and crispness without introducing artifacts.',
    badge: 'Converter',
    badgeVariant: 'neutral',
    iconName: 'FileImage',
    category: 'conversion',
    status: 'live',
    inputFormats: ['JPG', 'JPEG'],
    outputFormat: 'png',
    popular: true,
    features: ['Lossless conversion', 'High color fidelity', 'Instant browser export'],
  },
  {
    slug: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    shortName: 'PNG → JPG',
    tagline: 'Shrink bulky PNGs into lightweight JPEG photos',
    description: 'Convert PNG graphics and screenshots into optimized JPEG images for dramatically smaller file sizes and fast website loading.',
    badge: 'Converter',
    badgeVariant: 'neutral',
    iconName: 'RefreshCw',
    category: 'conversion',
    status: 'live',
    inputFormats: ['PNG'],
    outputFormat: 'jpg',
    popular: true,
    features: ['5x–10x file size reduction', 'Auto white-background fill', 'Adjustable quality'],
  },
  {
    slug: 'jpg-to-webp',
    name: 'JPG to WebP Converter',
    shortName: 'JPG → WebP',
    tagline: 'Next-generation WebP format for fast web delivery',
    description: 'Convert standard JPG photos into modern Google WebP format. Achieve 30%+ smaller file sizes with indistinguishable visual quality.',
    badge: 'Modern Web',
    badgeVariant: 'accent',
    iconName: 'Sparkles',
    category: 'conversion',
    status: 'live',
    inputFormats: ['JPG', 'JPEG'],
    outputFormat: 'webp',
    popular: true,
    features: ['30%+ smaller than JPEG', 'Boosts Core Web Vitals', 'Universal browser support'],
  },
  {
    slug: 'png-to-webp',
    name: 'PNG to WebP Converter',
    shortName: 'PNG → WebP',
    tagline: 'Smaller transparent images for websites and apps',
    description: 'Convert PNG images to WebP while fully preserving alpha transparency. Get significantly lighter files without losing transparency.',
    badge: 'Converter',
    badgeVariant: 'neutral',
    iconName: 'Layers',
    category: 'conversion',
    status: 'live',
    inputFormats: ['PNG'],
    outputFormat: 'webp',
    popular: false,
    features: ['Preserves alpha transparency', 'Up to 50% smaller than PNG', 'Lossless compression'],
  },
  {
    slug: 'webp-to-jpg',
    name: 'WebP to JPG Converter',
    shortName: 'WebP → JPG',
    tagline: 'Universal compatibility for WebP images',
    description: 'Convert downloaded WebP images to universally compatible JPEG format for easy viewing, editing, and sharing on any device.',
    badge: 'Converter',
    badgeVariant: 'neutral',
    iconName: 'ArrowRightLeft',
    category: 'conversion',
    status: 'live',
    inputFormats: ['WebP'],
    outputFormat: 'jpg',
    popular: false,
    features: ['100% universal compatibility', 'Compatible with old editors', 'Fast batch export'],
  },
  {
    slug: 'webp-to-png',
    name: 'WebP to PNG Converter',
    shortName: 'WebP → PNG',
    tagline: 'Extract lossless PNGs from WebP files',
    description: 'Convert WebP images to uncompressed PNG format with full transparency preservation for professional photo editing and design workflows.',
    badge: 'Converter',
    badgeVariant: 'neutral',
    iconName: 'Maximize2',
    category: 'conversion',
    status: 'live',
    inputFormats: ['WebP'],
    outputFormat: 'png',
    popular: false,
    features: ['Lossless pixel preservation', 'Full alpha channel support', 'Figma & Photoshop ready'],
  },

  {
    slug: 'image-resizer',
    name: 'Bulk Image Resizer',
    shortName: 'Resize Images',
    tagline: 'Exact dimensions or scale percentage in seconds',
    description: 'Batch resize image dimensions by percentage or target width/height with aspect-ratio locking.',
    badge: 'New',
    badgeVariant: 'primary',
    iconName: 'Maximize2',
    category: 'resizing',
    status: 'live',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: null,
    popular: true,
    features: ['Scale by % or pixels', 'Constrain proportions', 'High-quality bicubic resampling'],
  },
  {
    slug: 'image-cropper',
    name: 'Smart Image Cropper',
    shortName: 'Crop Image',
    tagline: 'Precision aspect-ratio crop for social & web',
    description: 'Crop images with preset ratios (16:9, 4:3, 1:1, 9:16) for YouTube, Instagram, LinkedIn, and web banners.',
    badge: 'New',
    badgeVariant: 'primary',
    iconName: 'Crop',
    category: 'resizing',
    status: 'live',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: null,
    popular: true,
    features: ['Social media aspect ratios', 'Pixel-precise crop box', 'Instant live preview'],
  },
  {
    slug: 'image-rotator',
    name: 'Image Rotator & Flipper',
    shortName: 'Rotate Image',
    tagline: 'Reorient 90/180/270 degrees or mirror horizontally/vertically',
    description: 'Fix photo orientation and mirror images horizontally or vertically in your browser memory.',
    badge: 'New',
    badgeVariant: 'primary',
    iconName: 'RotateCw',
    category: 'resizing',
    status: 'live',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: null,
    popular: false,
    features: ['Rotate 90°, 180°, 270°', 'Horizontal & vertical flip', 'Zero upload privacy'],
  },
  {
    slug: 'image-converter',
    name: 'Universal Image Converter',
    shortName: 'Convert Images',
    tagline: 'Universal in-browser image transcoding between JPG, PNG, and WebP',
    description: 'Convert between modern JPG, PNG, and WebP formats in browser RAM with parallel batch processing.',
    badge: 'New',
    badgeVariant: 'accent',
    iconName: 'RefreshCw',
    category: 'conversion',
    status: 'live',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: null,
    popular: true,
    features: ['Universal format transcoding', 'Alpha channel preservation', 'Batch ZIP download'],
  },
  {
    slug: 'background-remover',
    name: 'AI Background Remover',
    shortName: 'Remove BG',
    tagline: 'Automatic subject isolation with transparent PNG export',
    description: 'Automatically isolate human portraits, products, and graphics with high-precision edge detection.',
    badge: 'Roadmap',
    badgeVariant: 'upcoming',
    iconName: 'Wand2',
    category: 'utility',
    status: 'coming-soon',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: 'png',
    popular: false,
    features: ['Instant edge detection', 'Transparent PNG output', '1-click cutouts'],
  },
];

export const LIVE_TOOLS = IMAGE_TOOLS.filter((t) => t.status === 'live');
export const POPULAR_TOOLS = IMAGE_TOOLS.filter((t) => t.popular);
export const COMING_SOON_TOOLS = IMAGE_TOOLS.filter((t) => t.status === 'coming-soon');

export function getToolBySlug(slug) {
  return IMAGE_TOOLS.find((t) => t.slug === slug) || null;
}

export function getRelatedTools(slug, limit = 4) {
  const current = getToolBySlug(slug);
  if (!current) return LIVE_TOOLS.slice(0, limit);
  return LIVE_TOOLS.filter((t) => t.slug !== slug).slice(0, limit);
}

export function getMimeForFormat(format) {
  const map = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp' };
  return map[format] || 'image/jpeg';
}
